# Generated by Django 5.1.7 on 2025-05-21 12:37

import datetime
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountTransfer',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('trans_from', models.CharField(max_length=30)),
                ('trans_to', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CashGl',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('accno', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crdr', models.BooleanField(default=False)),
                ('trans_comt', models.TextField()),
                ('end_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('min_stock', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Compdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_path', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('mph', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('address', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlBal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glac', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_date', models.DateField()),
                ('income_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inctype', models.CharField(max_length=30)),
                ('income_taken', models.BooleanField(default=False)),
                ('received_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('invest_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('invest_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invest_desc', models.TextField()),
                ('source', models.TextField()),
                ('invest_to', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('min_stock', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_option', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('stock_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('purchase_seq', models.IntegerField(default=1)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('bill_year', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_seq', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('bill_year', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_seq', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_mph', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer', models.TextField()),
                ('mph', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('issue_details', models.TextField()),
                ('password', models.CharField(max_length=30)),
                ('paid_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paidpayment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('received_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('receivedpayment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receivable_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_status', models.CharField(default='Opened', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('bill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_accno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('payment_freq', models.CharField(max_length=15)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_date', models.DateField(default=datetime.date.today)),
                ('next_pay_date', models.DateField()),
                ('bal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paydate', models.DateField(blank=True, null=True)),
                ('lock_id', models.CharField(max_length=30)),
                ('ref_mph', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.customer')),
            ],
        ),
        migrations.CreateModel(
            name='GlHist',
            fields=[
                ('trans_seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_command', models.TextField()),
                ('credit', models.BooleanField(default=False)),
                ('debit', models.BooleanField(default=False)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_seq', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_type', models.CharField(max_length=20)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('int', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanJournal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('journal_seq', models.IntegerField()),
                ('journal_date', models.DateField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('old_data', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_data', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crdr', models.BooleanField(default=False)),
                ('trans_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='BillingModule.loan')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_seq', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='BillingModule.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_products',
            field=models.ManyToManyField(through='BillingModule.PurchaseItem', to='BillingModule.item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingModule.purchasepayment'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('bill_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sale_seq', models.IntegerField(default=1)),
                ('sale_date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingModule.customer')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingModule.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_seq', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='BillingModule.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_products',
            field=models.ManyToManyField(through='BillingModule.SaleItem', to='BillingModule.item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.seller'),
        ),
    ]
