# Generated by Django 5.1.7 on 2025-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
