# Generated by Django 5.1.7 on 2025-05-05 05:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0002_alter_brand_brand_name_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashGl',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('accno', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crdr', models.BooleanField(default=False)),
                ('trans_comt', models.TextField()),
                ('end_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='GlBal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.cashgl')),
            ],
        ),
    ]
