# Generated by Django 5.1.7 on 2025-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0003_cashgl_sale_income_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glbal',
            name='glac',
            field=models.CharField(max_length=30),
        ),
    ]
