# Generated by Django 5.1.7 on 2025-05-05 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0004_alter_glbal_glac'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='advance_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='advance_paydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
