# Generated by Django 5.1.7 on 2025-05-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0005_loan_advance_amt_loan_advance_paydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='advance_amt',
            new_name='advance_bal',
        ),
    ]
