# Generated by Django 5.1.7 on 2025-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0006_rename_advance_amt_loan_advance_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbill',
            name='due_type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
