# Generated by Django 5.1.7 on 2025-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0007_loanbill_due_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('invest_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('invest_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invest_desc', models.TextField()),
            ],
        ),
    ]
