# Generated by Django 5.1.7 on 2025-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0008_invest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_date', models.DateField()),
                ('income_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_taken', models.BooleanField(default=False)),
                ('received_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
