# Generated by Django 5.1.7 on 2025-05-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0009_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbill',
            name='int',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanbill',
            name='prin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
