# Generated by Django 5.1.7 on 2025-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0010_loanbill_int_loanbill_prin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='advance_paydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
