# Generated by Django 5.1.7 on 2025-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0011_alter_loan_advance_paydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='source',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
