# Generated by Django 5.1.7 on 2025-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0012_invest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='inctype',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
