# Generated by Django 5.1.7 on 2025-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0013_income_inctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='advance_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
