# Generated by Django 5.1.7 on 2025-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0014_loan_advance_amt_loan_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lock_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='ref_mph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
