# Generated by Django 5.1.7 on 2025-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0015_loan_lock_id_loan_ref_mph'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
