# Generated by Django 5.1.7 on 2025-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0016_category_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='min_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
