# Generated by Django 5.1.7 on 2025-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0017_alter_category_min_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountTransfer',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('trans_from', models.CharField(max_length=30)),
                ('trans_to', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
