# Generated by Django 5.1.7 on 2025-05-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0018_amounttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='invest_to',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
