# Generated by Django 5.1.7 on 2025-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0019_invest_invest_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer', models.TextField()),
                ('mph', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('issue_details', models.TextField()),
                ('password', models.CharField(max_length=30)),
                ('paid_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paidpayment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('received_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('receivedpayment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receivable_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_status', models.CharField(default='Opened', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('bill', models.IntegerField()),
            ],
        ),
    ]
