# Generated by Django 5.1.7 on 2025-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0019_invest_invest_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer', models.TextField()),
                ('mph', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('issue_details', models.TextField()),
                ('password', models.CharField(max_length=30)),
                ('paid_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
