# Generated by Django 5.1.7 on 2025-05-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0020_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
