# Generated by Django 5.1.7 on 2025-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0020_service_servicebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ln_typ',
            field=models.CharField(default='MOB', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanbill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
