# Generated by Django 5.1.7 on 2025-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0021_loan_ln_typ_loanbill_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
