# Generated by Django 5.1.7 on 2025-05-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0021_service_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
