# Generated by Django 5.1.7 on 2025-06-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0022_alter_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loanamt_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
