# Generated by Django 5.1.7 on 2025-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0022_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='paid_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='received_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
