# Generated by Django 5.1.7 on 2025-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0023_loan_loanamt_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='intRcvd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='penRcvd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='prinRcvd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
