# Generated by Django 5.1.7 on 2025-05-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0023_service_balance_alter_service_paid_amt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='service_status',
        ),
    ]
