# Generated by Django 5.1.7 on 2025-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0024_loan_intrcvd_loan_penrcvd_loan_prinrcvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='received_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
