# Generated by Django 5.1.7 on 2025-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0024_rename_status_service_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
