# Generated by Django 5.1.7 on 2025-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0025_income_received_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
