# Generated by Django 5.1.7 on 2025-05-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0025_service_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_chrg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.CharField(default='Opened', max_length=30),
        ),
    ]
