# Generated by Django 5.1.7 on 2025-05-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0026_service_service_chrg_alter_service_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_chrg',
            new_name='receivable_amt',
        ),
    ]
