# Generated by Django 5.1.7 on 2025-07-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0026_loan_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('date', models.DateField()),
                ('commited_in', models.IntegerField()),
                ('extended_date', models.DateField()),
                ('loan_accno', models.CharField(max_length=15)),
            ],
        ),
    ]
