# Generated by Django 5.1.7 on 2025-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0027_rename_service_chrg_service_receivable_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
