# Generated by Django 5.1.7 on 2025-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0027_loaninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
    ]
