# Generated by Django 5.1.7 on 2025-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0028_service_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('bill', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='paidpayment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='receivedpayment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
