# Generated by Django 5.1.7 on 2025-07-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0028_sale_reversed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaninfo',
            old_name='commited_in',
            new_name='committed_in',
        ),
        migrations.AlterField(
            model_name='loaninfo',
            name='loan_accno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_infos', to='BillingModule.loan'),
        ),
    ]
