# Generated by Django 5.1.7 on 2025-07-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0029_rename_commited_in_loaninfo_committed_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='intRcvd',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='penRcvd',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='prinRcvd',
        ),
    ]
