# Generated by Django 5.1.7 on 2025-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0030_remove_loan_intrcvd_remove_loan_penrcvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lock_sts',
            field=models.BooleanField(default=False),
        ),
    ]
