# Generated by Django 5.1.7 on 2026-01-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0031_loan_lock_sts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discmon',
            fields=[
                ('yearmon', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('discamt', models.IntegerField()),
            ],
        ),
    ]
